INSERT INTO ecolife.dbo.Product (Id, Name, Price, Quantity, Type, Image, Weight, Dimensions, Materials, Description, Status, Rate, CategoryId, discount) VALUES (1, N'Originals Kaval Windbr', 19, 100, null, N'/images/products/OriginalsKavalWindbr.jpg', N'400 g', N'10 x 10 x 15 cm', N'60% cotton, 40% polyester', N'Lorem ipsum dolor sit amet consectetur adipisicing elit, sed do eiusmod tempor incididunt

ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commo consequat. Duis aute irure dolor in reprehend in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt', null, 3, 2, 10);
INSERT INTO ecolife.dbo.Product (Id, Name, Price, Quantity, Type, Image, Weight, Dimensions, Materials, Description, Status, Rate, CategoryId, discount) VALUES (2, N'Juicy Couture Juicy Quilted T', 20, 100, null, N'/images/products/JuicyCoutureJuicyQuiltedT.jpg ', N'400 g', N'10 x 10 x 15 cm', N'60% cotton, 40% polyester', N'Lorem ipsum dolor sit amet consectetur adipisicing elit, sed do eiusmod tempor incididunt

ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commo consequat. Duis aute irure dolor in reprehend in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt', null, 4, 2, 10);
INSERT INTO ecolife.dbo.Product (Id, Name, Price, Quantity, Type, Image, Weight, Dimensions, Materials, Description, Status, Rate, CategoryId, discount) VALUES (3, N'New Balance Fresh Foam Ka', 20, 100, null, N'/images/products/NewBalanceFreshFoamKa.jpg', N'400 g', N'10 x 10 x 15 cm', N'60% cotton, 40% polyester', N'Lorem ipsum dolor sit amet consectetur adipisicing elit, sed do eiusmod tempor incididunt

ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commo consequat. Duis aute irure dolor in reprehend in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt', null, 4, 2, 10);
INSERT INTO ecolife.dbo.Product (Id, Name, Price, Quantity, Type, Image, Weight, Dimensions, Materials, Description, Status, Rate, CategoryId, discount) VALUES (4, N'Brixton Patrol All Terrain', 20, 100, null, N'/images/products/BrixtonPatrolAllTerrain.jpg', N'400 g', N'10 x 10 x 15 cm', N'60% cotton, 40% polyester', N'Lorem ipsum dolor sit amet consectetur adipisicing elit, sed do eiusmod tempor incididunt

ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commo consequat. Duis aute irure dolor in reprehend in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt', null, 4, 2, 10);
